resposta = input("Digite algo: ")

print(f"O tipo primitivo desse valor é {type(resposta)}")
print(f"É númerico? {resposta.isnumeric()}")
print(f"É alfabético? {resposta.isalpha()}")
print(f"É alfanúmerico? {resposta.isalnum()}")
print(f"Está em maiúsculas? {resposta.isupper()}")
print(f"Está em minúsculas? {resposta.islower()}")
print((f"Só tem espaços? {resposta.isspace()}"))
print(f"Está capitalizada? {resposta.istitle()}")