nome = input("Qual é seu nome? ")
print(f"Prazer em te conhecer {nome:=^20}!")

print("-"*20)

n1 = int(input('Digite um número: '))
n2 = int(input("Digite mais um número: "))

print("-"*20)
print(f"A soma vale {n1 + n2}")
print("-" *20)
print(f"A subtração vale {n1 - n2}")
print("-" *20)
print(f"A multiplicação vale {n1 * n2}")
print("-" *20)
print(f"A divisão vale {(n1 / n2):.3f}")
print("-" *20)
print(f"A potencia vale {n1 ** n2}")
print(f"-" *20)
print(f"A divisão usando apenas inteiros {n1 // n2}")
print("-"* 20)
print(f"O resto da divisão {n1 % n2}")
print("-" *20)
print("Tirando a quebra de linha, " ,end="")
print("pronto acabamos de tirar.")
print("-" *20)
print("Agora vamos quebrar linhas...\nAcabamos de quebra uma linha.")
print("-" *20)
print("Adicionamos algo no end" ,end=" >>> ")
print("Desta mandeira")